# If not running interactively, don't do anything
[ -z "$PS1" ] && return

ZSHDIR="$HOME/.dotfiles/zsh"

# TODO
# - https://github.com/peterhurford/git-it-on.zsh

# Core zsh config
source $ZSHDIR/lib/key-bindings.zsh
source $ZSHDIR/lib/git-prompt.zsh

# Plugins
source $ZSHDIR/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source $ZSHDIR/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source $ZSHDIR/plugins/zsh-completions/zsh-completions.plugin.zsh
source $ZSHDIR/plugins/calc/calc.plugin.zsh
source $ZSHDIR/plugins/fasd/fasd

# Custom config
source $ZSHDIR/mass.zsh
source $ZSHDIR/mass.zsh-theme
